spring:
  profiles:
    active: dev
    include:
      - springdoc
    group:
      local: springdoc-local
      test: springdoc-test
      dev: springdoc-dev
      beta: springdoc-beta
      prod: springdoc-prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
    org.hibernate.sql: debug